const illustrativeStandards = [
  {
    standardNumber: "IS 1786",
    title: "High strength deformed steel bars and wires for concrete reinforcement",
    category: "steel",
    testMethods: ["IS 1608", "IS 1599", "IS 1786"],
    alliedCodes: ["IS 456", "IS 2502"],
    certificationRequired: ["ISI Mark", "BIS QCO"],
    edition: "2008 + Amendments",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 432 (Part 1)",
    title: "Mild steel and medium tensile steel bars and hard-drawn steel wire for concrete reinforcement",
    category: "steel",
    testMethods: ["IS 1608", "IS 1599"],
    alliedCodes: ["IS 456", "IS 2502"],
    certificationRequired: ["ISI Mark"],
    edition: "1982 + Amendments",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 2062",
    title: "Hot rolled medium and high tensile structural steel",
    category: "steel",
    testMethods: ["IS 1608", "IS 1599", "IS 228"],
    alliedCodes: ["IS 800", "IS 808"],
    certificationRequired: ["ISI Mark", "BIS QCO"],
    edition: "2011 + Amendments",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 1079",
    title: "Hot rolled carbon steel sheet and strip",
    category: "steel",
    testMethods: ["IS 1608", "IS 513"],
    alliedCodes: ["IS 800", "IS 801"],
    certificationRequired: ["ISI Mark"],
    edition: "2017",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 4923",
    title: "Hollow steel sections for structural use",
    category: "steel",
    testMethods: ["IS 1608", "IS 228"],
    alliedCodes: ["IS 800", "IS 1161"],
    certificationRequired: ["ISI Mark"],
    edition: "1997",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 1161",
    title: "Steel tubes for structural purposes",
    category: "steel",
    testMethods: ["IS 2329", "IS 1608"],
    alliedCodes: ["IS 800", "IS 4923"],
    certificationRequired: ["ISI Mark"],
    edition: "2014",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 269",
    title: "Ordinary Portland cement, 33 grade",
    category: "cement",
    testMethods: ["IS 4031 (Parts 1-15)", "IS 650"],
    alliedCodes: ["IS 456", "IS 1489"],
    certificationRequired: ["ISI Mark", "BIS QCO"],
    edition: "2015",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 8112",
    title: "Ordinary Portland cement, 43 grade",
    category: "cement",
    testMethods: ["IS 4031 (Parts 1-15)", "IS 650"],
    alliedCodes: ["IS 456", "IS 269"],
    certificationRequired: ["ISI Mark", "BIS QCO"],
    edition: "2013",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 12269",
    title: "Ordinary Portland cement, 53 grade",
    category: "cement",
    testMethods: ["IS 4031 (Parts 1-15)", "IS 650"],
    alliedCodes: ["IS 456", "IS 8112"],
    certificationRequired: ["ISI Mark", "BIS QCO"],
    edition: "2013",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 1489 (Part 1)",
    title: "Portland pozzolana cement using fly ash",
    category: "cement",
    testMethods: ["IS 4031 (Parts 1-15)", "IS 1727"],
    alliedCodes: ["IS 456", "IS 3812"],
    certificationRequired: ["ISI Mark", "BIS QCO"],
    edition: "2015",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 455",
    title: "Portland slag cement",
    category: "cement",
    testMethods: ["IS 4031 (Parts 1-15)", "IS 4032"],
    alliedCodes: ["IS 456", "IS 12089"],
    certificationRequired: ["ISI Mark", "BIS QCO"],
    edition: "2015",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 4031",
    title: "Methods of physical tests for hydraulic cement",
    category: "cement",
    testMethods: ["Fineness", "Soundness", "Setting time", "Compressive strength"],
    alliedCodes: ["IS 650", "IS 1727"],
    certificationRequired: [],
    edition: "1996 + Amendments",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 694",
    title: "PVC insulated unsheathed and sheathed cables for working voltages up to and including 1100 V",
    category: "electrical",
    testMethods: ["IS 10810", "IS 8130"],
    alliedCodes: ["IS 732", "IS 1646"],
    certificationRequired: ["ISI Mark", "BIS QCO"],
    edition: "2010",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 1554 (Part 1)",
    title: "PVC insulated heavy duty electric cables for working voltages up to and including 1100 V",
    category: "electrical",
    testMethods: ["IS 10810", "IS 8130"],
    alliedCodes: ["IS 732", "IS 1646"],
    certificationRequired: ["ISI Mark"],
    edition: "1988 + Amendments",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 7098 (Part 1)",
    title: "Cross-linked polyethylene insulated thermoplastic sheathed cables for working voltages up to and including 1100 V",
    category: "electrical",
    testMethods: ["IS 10810", "IS 8130"],
    alliedCodes: ["IS 732", "IS 1646"],
    certificationRequired: ["ISI Mark", "BIS QCO"],
    edition: "1988",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 732",
    title: "Code of practice for electrical wiring installations",
    category: "electrical",
    testMethods: ["Insulation resistance", "Continuity", "Polarity"],
    alliedCodes: ["IS 3043", "IS 1646"],
    certificationRequired: [],
    edition: "2019",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 3043",
    title: "Code of practice for earthing",
    category: "electrical",
    testMethods: ["Earth resistance", "Continuity", "Electrode inspection"],
    alliedCodes: ["IS 732", "IS 5216"],
    certificationRequired: [],
    edition: "2018",
    status: "current",
    supersededBy: null,
  },
  {
    standardNumber: "IS 1293",
    title: "Plugs and socket-outlets for household and similar purposes",
    category: "electrical",
    testMethods: ["Temperature rise", "Mechanical strength", "Insulation resistance"],
    alliedCodes: ["IS 302", "IS 732"],
    certificationRequired: ["ISI Mark", "BIS QCO"],
    edition: "2019",
    status: "current",
    supersededBy: null,
  },
];

export default illustrativeStandards;

